import type { CostReport } from "../estimator/index.js";
import type { Recommendation } from "../analyzer/index.js";
import { escapeHtml } from "../utils/escape.js";

function fmtCost(n: number): string {
  if (n < 0.01) return "$" + n.toFixed(4);
  if (n < 1) return "$" + n.toFixed(3);
  return "$" + n.toFixed(2);
}

import { PRICING_DATE } from "../pricing/catalog.js";

export function generateHtmlReport(report: CostReport, recommendations: Recommendation[] = []): string {
  const rows = report.estimates
    .sort((a, b) => b.monthlyCost - a.monthlyCost)
    .map((e) => {
      const relFile = e.callSite.file.replace(report.root + "/", "");
      return `<tr>
        <td>${escapeHtml(relFile)}:${e.callSite.line}</td>
        <td>${escapeHtml(e.callSite.provider)}</td>
        <td>${escapeHtml(e.pricing?.model ?? "unknown")}</td>
        <td>${fmtCost(e.costPerCall)}</td>
        <td>${e.callSite.inLoop ? e.callSite.loopMultiplier + "x" : ""}</td>
        <td><strong>${fmtCost(e.monthlyCost)}</strong></td>
      </tr>`;
    }).join("\n");

  const providerRows = Object.entries(report.byProvider)
    .sort((a, b) => b[1] - a[1])
    .map(([p, c]) => `<tr><td>${escapeHtml(p)}</td><td>${fmtCost(c)}</td><td>${((c / report.totalMonthlyCost) * 100).toFixed(0)}%</td></tr>`)
    .join("\n");

  const recRows = recommendations.map((r) => {
    const icon = r.type === "model-downgrade" ? "⬇️" : r.type === "caching" ? "💾" : "📦";
    return `<tr>
      <td>${icon} ${escapeHtml(r.type)}</td>
      <td>${escapeHtml(r.file.replace(report.root + "/", ""))}:${r.line}</td>
      <td>${escapeHtml(r.description)}</td>
      <td>${fmtCost(r.estimatedSavings)}</td>
    </tr>`;
  }).join("\n");

  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>LLM Cost Attribution Report</title>
<style>
  :root { --bg: #0d1117; --fg: #c9d1d9; --accent: #58a6ff; --green: #3fb950; --border: #30363d; }
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family: -apple-system, system-ui, sans-serif; background: var(--bg); color: var(--fg); padding: 2rem; }
  h1 { color: var(--accent); margin-bottom: 0.5rem; }
  .stats { display: flex; gap: 2rem; margin: 1rem 0 2rem; }
  .stat { background: #161b22; border: 1px solid var(--border); border-radius: 8px; padding: 1rem 1.5rem; }
  .stat-value { font-size: 1.5rem; font-weight: bold; color: var(--green); }
  .stat-label { font-size: 0.85rem; color: #8b949e; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
  th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid var(--border); font-size: 0.9rem; }
  th { background: #161b22; color: var(--accent); font-weight: 600; }
  tr:hover { background: #161b2288; }
  h2 { color: var(--accent); margin: 2rem 0 0.5rem; font-size: 1.2rem; }
  .footer { margin-top: 3rem; color: #8b949e; font-size: 0.8rem; }
</style>
</head><body>
<h1>LLM Cost Attribution Report</h1>
<p style="color:#8b949e">${escapeHtml(report.root)} | Pricing as of ${PRICING_DATE}</p>
<div class="stats">
  <div class="stat"><div class="stat-value">${report.filesScanned}</div><div class="stat-label">Files Scanned</div></div>
  <div class="stat"><div class="stat-value">${report.totalCallSites}</div><div class="stat-label">LLM Call Sites</div></div>
  <div class="stat"><div class="stat-value">${fmtCost(report.totalMonthlyCost)}</div><div class="stat-label">Est. Monthly Cost</div></div>
</div>
<h2>Call Sites</h2>
<table><thead><tr><th>File</th><th>Provider</th><th>Model</th><th>$/call</th><th>Loop</th><th>$/month</th></tr></thead>
<tbody>${rows}</tbody></table>
<h2>Cost by Provider</h2>
<table><thead><tr><th>Provider</th><th>Monthly Cost</th><th>Share</th></tr></thead>
<tbody>${providerRows}</tbody></table>
${recommendations.length > 0 ? `<h2>Optimization Opportunities</h2>
<table><thead><tr><th>Type</th><th>File</th><th>Description</th><th>Savings</th></tr></thead>
<tbody>${recRows}</tbody></table>` : ""}
<div class="footer">Generated by llm-cost-attr | ${new Date().toISOString()}</div>
</body></html>`;
}
